commit_message: '[CI SKIP]'
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
    translation_replace:
      values-en-rUS/strings.xml: values/strings.xml
bundles:
  - 4
